import Head from "next/head";
import styles from "../styles/Home.module.css";
import useWindowDimensions from "../src/hooks/windowSize";
import Container from "../src/components/container600";
import GaleryItem from "../src/components/sections/galleryitem";
import dynamic from "next/dynamic";

const DynamicComponentWithNoSSR = dynamic(
  () => import("../src/components/navbar"),
  { ssr: false }
);

export default function Gallery() {
  const { width } = useWindowDimensions();
  const currentPage = "Gallery";
  const pictures = [
    "chicken.png",
    "brisket.png",
    "beansclose.png",
    "chickens.png",
    "closed.png",
    "closeup.png",
    "macclose.png",
    "meats.png",
    "openfront.png",
    "openside.png",
    "poppers.png",
    "pork.png",
    "pulledpork.png",
    "pulledporkclose.png",
    "pulledporks.png",
  ];

  return (
    <div>
      <Head>
        <title>The Catering Vets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>
      </Head>
      <DynamicComponentWithNoSSR
        width={width}
        page={currentPage}
        links={["Home", "Menu", "Gallery"]}
      />

      <Container
        style={{
          backgroundImage:
            "url(https://images.unsplash.com/photo-1508615263227-c5d58c1e5821?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80)",
          backgroundPositionX: "50%",
          backgroundPositionY: "50%",
          backgroundSize: "cover",
        }}
      >
        <h1>Make Your Event Memorable</h1>
        <h3>Hire the Catering Vets</h3>
      </Container>

      <Container
        style={{ display: "block", textAlign: "center", margin: "50px" }}
      >
        {pictures.map((item, idx) => {
          return (
            <GaleryItem style={{ margin: "20px" }} item={item} idx={idx} />
          );
        })}
      </Container>

      <footer className={styles.footer}>
        © Catering Vets, All Rights Reserved
      </footer>
    </div>
  );
}
