import Head from "next/head";
import styles from "../styles/Home.module.css";
import useWindowDimensions from "../src/hooks/windowSize";
import Navbar from "../src/components/navbar";
import Container from "../src/components/container600";

export default function Home() {
  const { width } = useWindowDimensions();
  const currentPage = "Home";

  return (
    <div>
      <Head>
        <title>The Catering Vets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>
      </Head>

      <Navbar
        width={width}
        page={currentPage}
        links={["Home", "Menu", "About", "Contact"]}
      />

      <Container
        style={{
          backgroundImage:
            "url(https://images.unsplash.com/photo-1508615263227-c5d58c1e5821?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80)",
          backgroundPositionX: "50%",
          backgroundPositionY: "50%",
          backgroundSize: "cover",
        }}
      >
        <h1>Make Your Event Memorable</h1>
        <h3>Hire the Catering Vets</h3>
      </Container>

      <Container style={{}}>
        <div
          className="row"
          style={{ width: "100%", margin: "auto", maxWidth: "1400px" }}
        >
          <div className="col-lg-1"></div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <h5
              style={{
                textAlign: "center",
              }}
            >
              {" "}
              {"(256)-541-2553"}
            </h5>
            <h2
              style={{
                textAlign: "center",
              }}
            >
              Huntsville Based BBQ Catering
            </h2>
            <p
              style={{
                textAlign: "center",
              }}
            >
              We are veterans turned BBQ cooks. We want to share our passion
              good old fashioned BBQ with the rest of the North Alabama Area.
              Take a look at our menu and give us a call!
            </p>
            <button
              className="btn btn-primary"
              type="button"
              data-bs-toggle="offcanvas"
              data-bs-target="#offcanvasTop"
              aria-controls="offcanvasTop"
              style={{ width: "150px", height: "50px", fontSize: "1.3rem" }}
            >
              Menu
            </button>
          </div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <img
              style={{ height: "300px", margin: "20px" }}
              src="https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2850&q=80"
            ></img>
          </div>
          <div className="col-lg-1"></div>
        </div>
      </Container>

      <Container style={{}}>
        <div
          className="row"
          style={{ width: "100%", margin: "auto", maxWidth: "1400px" }}
        >
          <div className="col-lg-1"></div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <img
              style={{ height: "300px", margin: "20px" }}
              src="https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2850&q=80"
            ></img>

            <p>
              {" "}
              We offer service for weddings, graduations, family reunions,
              company picnics, family backyard BBQ, memorial services, as well
              as holiday parties and concession events. We provide services all
              year-round.{" "}
            </p>
          </div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <img
              style={{ height: "300px", margin: "20px" }}
              src="https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2850&q=80"
            ></img>

            <p>
              The Catering Vets is a family owned and operated business. We
              pride ourselves on our fine homemade dishes and great service. Our
              drop off service is what sets us apart from the rest. We deliver
              your food hot, fresh and right to your event.
            </p>
          </div>
          <div className="col-lg-1"></div>
        </div>
      </Container>
      <Container
        style={{ height: "300px", backgroundColor: "black", color: "white" }}
      >
        <div
          className="row"
          style={{ width: "100%", margin: "auto", maxWidth: "1400px" }}
        >
          <div className="col-lg-1"></div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum
            </p>
          </div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum
            </p>
          </div>
          <div className="col-lg-1"></div>
        </div>
      </Container>
      <Container
        style={{ height: "300px", backgroundColor: "#143306", color: "white" }}
      >
        <div className="row" style={{ width: "100%", margin: "auto" }}>
          <div className="col-lg-1"></div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum
            </p>
          </div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum
            </p>
          </div>
          <div className="col-lg-1"></div>
        </div>
      </Container>

      <footer className={styles.footer}>
        © Catering Vets, All Rights Reserved
      </footer>
    </div>
  );
}
