import Head from "next/head";
import styles from "../styles/Home.module.css";
import useWindowDimensions from "../src/hooks/windowSize";
import Container from "../src/components/container600";
import dynamic from 'next/dynamic'
import Image from "next/image"

const DynamicComponentWithNoSSR = dynamic(
  () => import("../src/components/navbar"),
  { ssr: false }
)



export default function Home() {
  const { width } = useWindowDimensions();
  const currentPage = "Home";

  return (
    <div>
      <Head>
        <title>The Catering Vets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous"
        ></link> */}
        
       
      </Head>
      <DynamicComponentWithNoSSR width={width}
        page={currentPage}
        links={["Home", "Menu", "Gallery"]}/>

      <Container
        style={{
          backgroundImage: "url(https://images.unsplash.com/photo-1508615263227-c5d58c1e5821?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80)",
          backgroundPositionX: "50%",
          backgroundPositionY: "50%",
          backgroundSize: "cover",
        }}
      >
        <h1>Make Your Event Memorable</h1>
        <h3>Hire the Catering Vets</h3>
      </Container>

      <Container style={{ textAlign: "center", minHeight: "500px", marginTop: "50px" }}>
        <div
          className="row"
          style={{ width: "100%", margin: "auto", maxWidth: "1400px" }}
        >
          <div className="col-lg-1"></div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <h5
              style={{
                textAlign: "center",
              }}
            >
              {" "}
              {"(256)-541-2553"}
            </h5>
            <h2
              style={{
                textAlign: "center",
              }}
            >
              Huntsville Based BBQ Catering
            </h2>
            <p
              style={{
                textAlign: "center",
              }}
            >
              We are veterans turned BBQ cooks. We want to share our passion
              good old fashioned BBQ with the rest of the North Alabama Area.
              You have an event? You let us know!
            </p>
            <a
              className="btn btn-primary"
              type="button"
              href="/Menu"
              style={{
                width: "150px",
                height: "50px",
                fontSize: "1.3rem",
                backgroundColor: "black",
              }}
            >
              Menu
            </a>
          </div>
          <div
            className="col-lg-5"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Image
              priority={true}
              width={385.59}
              height={300}
              src="/images/logo.png"
            ></Image>

          </div>
          <div className="col-lg-1"></div>
        </div>
      </Container>


      <Container
        style={{ minHeight: "300px", backgroundColor: "black", color: "white" }}
      >
        <div
          className="row"
          style={{ width: "100%", margin: "auto", maxWidth: "1400px" }}
        >
          <div
            className="col-lg-6"
            style={{
              display: "flex",
              justifyContent: "flex-start",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
           <Image
              width={1000}
              height={1000}

              src="/images/smoking.png"
              objectFit="contain"
            ></Image>
          </div>
          <div
            className="col-lg-6"
            style={{
              display: "flex",
              justifyContent: "center",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <p style={{textAlign: "start", fontSize: "1.1rem"}}>
              Our food is made with fresh and high quality ingredients. We smoke our pork, chicken, and ribs to perfection. Our meat is melt in your mouth tender ready for your guests plates. And we have delicious sides like Mac n' Cheese, Cole Slaw, and Baked Beans
            </p>
          </div>
        </div>
      </Container>
      
      <footer className={styles.footer}>
        © Catering Vets, All Rights Reserved
      </footer>
    </div>
  );
}
